import streamlit as st
import base64
from datetime import datetime

# 1. 기본 설정
st.set_page_config(page_title="독서노트", page_icon="📚")
st.title("📚 북리더 하이라이트 정리")

# 2. 스마트 필터링 파싱 함수 (쓰레기 데이터 제거)
def parse_mrexpt(file_bytes, filename):
    try:
        content = file_bytes.decode('utf-8')
    except UnicodeDecodeError:
        content = file_bytes.decode('cp949', errors='ignore')
        
    lines = content.splitlines()
    if not lines:
        return None

    book_title = filename.replace(".mrexpt", "")
    highlights = []
    
    for line in lines:
        text = line.strip()
        # [필터링 로직]
        if not text: continue # 빈 줄 제외
        if text.isdigit(): continue # 숫자만 있는 줄(좌표, 시간) 제외
        if len(text) <= 2: continue # 2글자 이하의 의미 없는 파편(o, f, 1 등) 제외
        if text.startswith('/storage') or text.startswith('/sdcard') or text.startswith('content://'): continue # 파일 경로 제외
        
        highlights.append(text)
            
    return {
        "title": book_title,
        "updated_at": datetime.now().strftime("%y.%m.%d %H:%M"),
        "highlights": highlights
    }

# 3. 다운로드용 예쁜 HTML 생성 함수
def generate_html(book_data):
    title = book_data['title']
    highlights = book_data['highlights']
    
    # HTML 및 CSS 디자인 (원본 프로젝트처럼 깔끔한 스타일 적용)
    html_content = f"""
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{title} - 하이라이트</title>
        <style>
            body {{ font-family: 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f9f9f9; }}
            h1 {{ color: #2c3e50; text-align: center; padding-bottom: 10px; border-bottom: 2px solid #3498db; }}
            .highlight-box {{ background: #fff; border-left: 4px solid #f1c40f; padding: 15px 20px; margin-bottom: 15px; border-radius: 4px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }}
            .footer {{ text-align: center; font-size: 0.8em; color: #7f8c8d; margin-top: 40px; }}
        </style>
    </head>
    <body>
        <h1>📘 {title}</h1>
        <p style="text-align: right; color: #7f8c8d;">생성일: {book_data['updated_at']}</p>
    """
    
    for hl in highlights:
        html_content += f'<div class="highlight-box">{hl}</div>\n'
        
    html_content += """
        <div class="footer">Generated by 문리더 대시보드</div>
    </body>
    </html>
    """
    return html_content

# 세션 초기화
if "books_db" not in st.session_state:
    st.session_state.books_db = {}

# 4. 파일 업로드 UI
with st.expander("⚙️ 파일 업로드", expanded=not bool(st.session_state.books_db)):
    uploaded_files = st.file_uploader("📂 .mrexpt 파일 추가", type=["mrexpt"], accept_multiple_files=True)

    if uploaded_files:
        for file in uploaded_files:
            bytes_data = file.read()
            parsed_data = parse_mrexpt(bytes_data, file.name)
            
            if parsed_data:
                title = parsed_data["title"]
                st.session_state.books_db[title] = parsed_data

st.divider()

# 5. 메인 뷰어 및 다운로드 화면
if st.session_state.books_db:
    book_list = list(st.session_state.books_db.keys())
    selected_book = st.selectbox("📖 처리된 책을 선택하세요", book_list)
    book_data = st.session_state.books_db[selected_book]
    
    st.markdown(f"### {book_data['title']}")
    
    # 🌟 HTML 파일 다운로드 버튼 생성
    html_string = generate_html(book_data)
    st.download_button(
        label="📥 HTML 파일로 다운로드 (개인 소장용)",
        data=html_string,
        file_name=f"{book_data['title']}_하이라이트.html",
        mime="text/html",
        type="primary" # 버튼을 눈에 띄게 파란색으로 표시
    )
    
    st.caption(f"총 {len(book_data['highlights'])}개의 하이라이트가 깔끔하게 정리되었습니다.")
    st.write("")
    
    # 화면 미리보기 (옵션)
    with st.container(border=True):
        st.markdown("**미리보기 (처음 3개만 표시)**")
        for idx, hl in enumerate(book_data["highlights"][:3]):
            st.markdown(f"> {hl}")
            if idx < 2: st.divider()
        if len(book_data["highlights"]) > 3:
            st.caption("... (나머지는 다운로드한 파일에서 확인하세요)")

else:
    st.info("상단의 '파일 업로드'를 눌러 문리더 백업 파일을 추가해 주세요.")
